# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['4.2', '4.4', '5.0', '6.0']
    
    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
      
    - name: Build package
      run: |
        cd ./source/server/cmd
        go build -v -o server
    
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        mongodb-username: TestUser
        mongodb-password: testPassword
        mongodb-db: weGoNiceTest
        
    - name: Run Tests
      run: |
        cd ./source/server/pkg
        go test users
        go test authors

