name: Renovate
on:
  [push]
  # schedule:
  # Runs on 08:05 every sunday
  # - cron: '5 8 * * 0'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v38.1.7
        with:
          configurationFile: renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
