# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: test-server

on: [push]

env:
  MONGO_INITDB_DATABASE: weGoNiceTest
  MONGO_INITDB_USERNAME: TestUser
  MONGO_INITDB_PASSWORD: testPassword

jobs:
  container-job:
    name: server-test
    runs-on: ubuntu-latest
    
    container:
      image:  golang:1.18-buster
      
    steps:
    - uses: actions/checkout@v1
    - run: |
        cd ./source/server/pkg
        go test ./users
        go test ./authors

    services:
      mongodb:
        image: mongo
        env:
          MONGO_INITDB_USERNAME: ${MONGO_INITDB_USERNAME}
          MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PASSWORD}
          MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
        volumes:
          - ./source/server/build/development/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
        ports:
        - 27020-27022:27017-27019


