# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: test-server

on: [push]

env:
  MONGO_INITDB_DATABASE: weGoNiceTest
  MONGO_INITDB_USERNAME: TestUser
  MONGO_INITDB_PASSWORD: testPassword
  TEST_DB_URI: mongodb://mongodb:27020

jobs:
  container-job:
    name: server-test
    runs-on: ubuntu-latest
    
    container:
      image:  golang:1.18-buster
      
    steps:
    - uses: actions/checkout@v1
    - run: |
        echo ${{github.workspace}}
        ls -l
        cd ./source/server/pkg
        ls -l
        go test ./users
        go test ./authors

    services:
      mongodb:
        image: mongo
        env:
          MONGO_INITDB_USERNAME: ${MONGO_INITDB_USERNAME}
          MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PASSWORD}
          MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
          TEST_DB_URI: ${TEST_DB_URI}
        volumes:
          - ${{github.workspace}}/source/server/build/development/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
        options: >-
          --health-cmd "echo 'db.runCommand("ping").ok' | mongosh --quiet"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
        - 27020-27022:27017-27019


